### ISSUE TITLE
Wrong language detection

### ISSUE THREAD

**Issue by lakejason0** [Litarvan/lightdm-webkit-theme-litarvan#168]
I was using Arch Linux. I chose zh-CN as the system language but it shows zh-TW instead. I manually set the LANG variable to `zh_CN.UTF-8` for lightdm but it's still the same. By setting it to zh-TW won't show zh-CN instead and by manually commenting out zh-TW it shows English. The content of `/etc/locale.conf` won't effect lightdm as it always choose English.

**Edit:** This no longer happens when `zh_TW.UTF-8` is removed from `locale.gen`. Idk if it's whose fault so I'll keep this issue here. If it's not at your end please tell me and close this issue.

**Comment by Litarvan** [comment]
Sadly it's not on my end, this probably comes from `lightdm-webkit2-greeter` which isn't maintained anymore, I probably can't do anything about it :(

**Comment by lakejason0** [comment]
Just changed back to this theme (webkit2gtk broke at a point), and that PR doesn't fix my issue.

**Comment by ZaynChen** [comment]
Try set the greeter to the debug mode, put `console.log(lang)` & `console.log(lightdm.language)` at the end of the `getLocal()` function before return, and restart the greeter, check the console in the devtools of the greeter page  to see whether `lang` is `zh-CN` & `lightdm.language` is `zh_CN.utf8`. If `lightdm.language` is not `zh_CN.utf8`, this may caused by your sys language config, not the greeter or this theme. I use this theme with `sea-greeter`, it just works fine, so I don't know why this PR not works for u. My archlinux is not with me now, so I can not check it these days.

**Comment by lakejason0** [comment]
> Try set the greeter to the debug mode, put `console.log(lang)` & `console.log(lightdm.language)` at the end of the `getLocal()` function before return, and restart the greeter, check the console in the devtools of the greeter page to see whether `lang` is `zh-CN` & `lightdm.language` is `zh_CN.utf8`. If `lightdm.language` is not `zh_CN.utf8`, this may caused by your sys language config, not the greeter or this theme. I use this theme with `sea-greeter`, it just works fine, so I don't know why this PR not works for u. My archlinux is not with me now, so I can not check it these days.

well, lightdm.langauge is `中文`. However, the debug menu is still in Simplified Chinese even if the theme is using zh-TW.

**Comment by ZaynChen** [comment]
That's weird. From the [lightdm](https://github.com/canonical/lightdm)'s source file [language.c](https://github.com/canonical/lightdm/blob/main/liblightdm-gobject/language.c#L149), we can see that `LightDMLanguage` has `code`, `name`, `territory`, and is an element from `lightdm_get_languages()`. And [web-greeter(lightdm-webkit2-greeter)](https://github.com/Antergos/web-greeter)'s `lightdm.language` & `lightdm.languages` should call lightdm's `lightdm_get_language()` and  `ligthdm_get_languages()` respectively to get the current language and language list. So the type of `lightdm.language` and the element of `lightdm.languages` should be the same. From you case, the `name` & `territory` should be `中文` and `''` respectively in the PR code, and using  only `name` can not distinguish the `zh_CN` & `zh_TW`, so it go to the `else` condition block. Did u try other themes? If other themes can distinguish `zh_CN` & `zh_TW`, then the problem should caused by this theme. In short, this issue should be caused by `ligthdm.lanuage`, if it is an string, it will be the name of current language, and if it is an object, it should have `code`, `name` & `territory`, and this issue can not be solved by this PR. For sea-greeter, you can try this [script](https://github.com/ZaynChen/dotfiles/blob/master/bin/install_basic_apps.sh#L9) to setup.

**Comment by lakejason0** [comment]
> That's weird. From the [lightdm](https://github.com/canonical/lightdm)'s source file [language.c](https://github.com/canonical/lightdm/blob/main/liblightdm-gobject/language.c#L149), we can see that `LightDMLanguage` has `code`, `name`, `territory`, and is an element from `lightdm_get_languages()`. And [web-greeter(lightdm-webkit2-greeter)](https://github.com/Antergos/web-greeter)'s `lightdm.language` & `lightdm.languages` should call lightdm's `lightdm_get_language()` and `ligthdm_get_languages()` respectively to get the current language and language list. So the type of `lightdm.language` and the element of `lightdm.languages` should be the same(From the [js api doc](https://doclets.io/Antergos/web-greeter/stable#dl-LightDM-Language). From your case, the `name` & `territory` should be `中文` and `''` respectively in the PR code, and using only `name` can not distinguish the `zh_CN` & `zh_TW`, so it go to the `else` condition block. Did u try other themes? If other themes can distinguish `zh_CN` & `zh_TW`, then the problem should caused by this theme.
> 
> In short, this issue should be caused by `lightdm.language`, if it is a string, it will be the name of current language, and if it is an object, it should have `code`, `name` & `territory`, and this issue can not be solved by this PR.
> 
> For sea-greeter, you can try this [script](https://github.com/ZaynChen/dotfiles/blob/master/bin/install_basic_apps.sh#L9) to setup.

(I'll just use Chinese, I'm running out of time)
很遗憾，您给的脚本跟我当时安装的步骤基本一致。即使添加了您所编写的额外设置，sea-greeter依然无法正确启动，开机即黑屏。我会尝试其他主题的。

**Comment by ZaynChen** [comment]
@lakejason0  你能确认一下分支 [migrate2vue3](https://github.com/ZaynChen/lightdm-webkit-theme-litarvan/tree/migrate2vue3) 是否解决了这个问题。我在 `lightdm.users` 里看到 `user` 有 `language： zh_CN.UTF-8` 这个属性，所以在 getLocale 时采用 `user.language` 而不用 `lightdm.language`，目前在我的 archlinux 是可以运行，采用的环境是 `lightdm 1:1.32.0-4`， `lightdm-webkit2-greeter 2.2.5-6`，`webkit2gtk 2.40.1-1`， `webkit2gtk-4.1 2.40.1-1`。我想确认一下在其他机器环境下是否有效

**Comment by lakejason0** [comment]
> @lakejason0  你能确认一下分支 [migrate2vue3](https://github.com/ZaynChen/lightdm-webkit-theme-litarvan/tree/migrate2vue3) 是否解决了这个问题。我在 `lightdm.users` 里看到 `user` 有 `language： zh_CN.UTF-8` 这个属性，所以在 getLocale 时采用 `user.language` 而不用 `lightdm.language`，目前在我的 archlinux 是可以运行，采用的环境是 `lightdm 1:1.32.0-4`， `lightdm-webkit2-greeter 2.2.5-6`，`webkit2gtk 2.40.1-1`， `webkit2gtk-4.1 2.40.1-1`。我想确认一下在其他机器环境下是否有效

挺好，但是我已经在用替代的greeter了（毕竟lightdm-webkit2-greeter似乎真的没维护）
