### ISSUE TITLE
Logging in does not work

### ISSUE THREAD

**Issue by wundrweapon** [Litarvan/lightdm-webkit-theme-litarvan#27]
So I finally got it to run as intended, but now I have a new problem. Putting in any password - any at all, real or fake - then hitting enter will lock the password box and do nothing. Backing up to the "press enter/space" menu will clear and unlock the password box, but regardless there's neither a login nor a notification that the password is incorrect.

Sidenote: the animations are extremely laggy (to the point of slowing the entire greeter down) on my machine, despite working fine on the live test site

**Comment by Litarvan** [comment]
I once had such a lag, it was because i had no proper graphical driver, it worked when i installed the right one despite being on a simple pentium chipset.

I use simple CSS transitions, if you d'ont find any way to fix the lag i'll add a way to disable animations. 

About the login issue, it looks like an issue with your lightdm webkit version, i'll need lightdm logs to know.

**Comment by wundrweapon** [comment]
>I once had such a lag, it was because i had no proper graphical driver
The proprietary drivers I'm using don't run until logged in, but the nouveau drivers don't do well with games...

>i'll need lightdm logs
[Here you go](https://hastebin.com/avihicujop.cs)

**Comment by Litarvan** [comment]
Can't do anything for your graphical drivers, i'll add an option to disable animations.
For the logs, it looks like the theme is trying to log you with no username, it's very strange.

On the login screen, at the bottom of the avatar, should be display "<Display name> / <username>", do you have username displayed ?

If you do, it may be because of a different lightdm-webkit version, don't you have a log file such as /var/log/lightdm/seat-0.log ? It's where javascript console is, and also some other useful informations.

**Comment by Litarvan** [comment]
Very strange, as i said probably an issue with your lightdm version. What distro are you using ? Do you have it up to date ? Also, can you tell me about your username being displayed as I said in my previous message ?

**Comment by wundrweapon** [comment]
I'm running Void, and I've confirmed everything is up-to-date. The username and profile image are displayed as expected.

**Comment by Litarvan** [comment]
I'm kinda stuck here. It may be, too much up to date ? I mean it definetely looks like the webkit API changed, which version of lightdm webkit do you have ? (It does not work with the web-greeter next).

Could you test from your desktop from a terminal ? Enable `debug_mode` in `/usr/share/lightdm/lightdm-webkit.conf`, and launch `lightdm-webkit2-greeter` from a terminal, and open the dev tools console. Login and then try to send me any strange output.

**Comment by Litarvan** [comment]
This appear to be linked to the blur lags issue. 3.2.0 added a 'blur settings' view where you can tweak it as you need, it will probably fix your issue. Please let me know if it's still there.
