### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by FFY00** [Litarvan/lightdm-webkit-theme-litarvan#68]
Hey, since https://github.com/Antergos/web-greeter has been archived I was wondering about the future of the project. This is a great theme and it would be a shame to see it go away in the future. Do you have any plans?

**Comment by Litarvan** [comment]
Hey ! First of all, again, thanks a lot for your interest in the project and for maintaining it on the Arch repos.
In fact, when the project was archived, i was a bit demotivated, also because i thought of a lot of things for the v3 and the limitations of web-greeter didn't make me able to do all of them.

I wanted to rework the greeter on GTK, but I don't have the time for this (i must learn Rust better and GTK first, and also LightDM ofc) so I'll delay this for now (my studies takes me time too), and decided to (finally) release the v3 with everything i could do.

So the future is : v3 for now (i just released it), and a GTK reworked version of the theme in the future

I think it's ready so if you are good with it you can update it! (and again, thanks a lot !)

**Comment by FFY00** [comment]
No problem! The theme is really good!

We are good for now but we need to keep a look on webkit2gtk as I that seems like the most likely breaking point. In last resource I could probably maintain an older version of webkit2gtk, and eventually gtk, in the arch repos to keep the theme working.

As far as the development for the theme itself goes, I have done some stuff in gtk and it's really not that hard so I think you will have much issues. But still, porting it should take a fair bit of time and as a student it might be a little hard. I would help if I could but unfortunately I am not proficient in any of the needed languages (I mostly do C, Python and D).

With that said I just wanted to thank you for your work and say that I am eager to see what comes next!
