### ISSUE TITLE
Trouble loading litarvan theme for webkit

### ISSUE THREAD

**Issue by illuminati-RV** [Litarvan/lightdm-webkit-theme-litarvan#7]
I recently installed litarvan on my Manjaro linux 17.0.6 with **lightdm-webkit2-greeter configured** properly,
I get a **blinking screen on loading lightdm**. It then asks me to **load the default or fallback** theme...

[seat0-greeter.log](https://github.com/Litarvan/lightdm-webkit-theme-litarvan/files/1449979/seat0-greeter.log)

This is the log file of the same, pls help me out!

**Comment by lordcriswat** [comment]
Go to the AUR Page (In the description) and install it with makepkg -cris, then edit lightdm-webkit2-greeter.conf
That's what worked for me. I got the same error as you trying to do it manually... maybe there is a step in the PKGBUILD that i've been missing. Might be worth reading it.

**Comment by Litarvan** [comment]
I have to admit the code is not so clean.
In fact it looks likes it caused by some missing value, it can be your username or something but it really shouldn't happen as even the default theme looks like crashing when i look at the code.

What version of lightdm-webkit2-greeter do you have ? Notice that a good way to test the theme is to run "lightdm-webkit2-greeter" command on a terminal, you could then send me the log if an error is displayed on the terminal

**Comment by Litarvan** [comment]
Closed for inactivity

**Comment by DasFranck** [comment]
I ran into this problem today. The exact same problem with the same errors.  
And I just found some minutes ago after half an hour of check-everything-even-the-theme-code-just-in-case what was the problem because this line was bothering me:
```
** (WebKitWebProcess:2629): CRITICAL **: lightdm_language_get_name: assertion 'LIGHTDM_IS_LANGUAGE (language)' failed
```

And the reason was...
```
$ localectl list-locales
fr_FR.utf8
```

```
$ cat /etc/locale.conf
LANG=en_GB.UTF-8
```

Yep. Turns out my locale was just not generated. (I use both fr_FR and en_GB but forgot to generate en_GB).  
I hate myself so much, but hey it's fixed and hopefully I've saved some time for the next one who will commit this error. :slightly_smiling_face:
